# Generated by Django 4.2.4 on 2023-09-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='abc', upload_to='images'),
            preserve_default=False,
        ),
    ]
