# Generated by Django 4.2.4 on 2023-09-03 13:41

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventList', '0002_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.CharField(default='---link----', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 3, 13, 41, 42, 390515, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
