# Generated by Django 4.2.6 on 2023-10-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventList", "0003_event_end_date_event_link_event_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
