# Generated by Django 4.2.6 on 2023-10-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventList", "0004_alter_event_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="shown",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
